apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tgbot-ns
resources:
  - k8s/bot-deployment.yaml
secretGenerator:
  - name: bot-secrets
    envs:
      - .env
    type: Opaque
