apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: private

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-data-pvc.yaml
  - postgres-backup-pvc.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - migration-job.yaml
  - telegram-deployment.yaml
  - vk-deployment.yaml
  - postgres-backup-cronjob.yaml

images:
  - name: detective-bot-image
    newName: evmhub/detective-bot
    newTag: 72de66b
