apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detective-bot-postgres-data
  labels:
    app.kubernetes.io/name: detective-bot-postgres
    app.kubernetes.io/part-of: detective-bot
    detective-bot.io/deployment-phase: foundation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-prov
  resources:
    requests:
      storage: 5Gi
