apiVersion: v1
kind: Service
metadata:
  name: detective-bot-postgres
  labels:
    app.kubernetes.io/name: detective-bot-postgres
    app.kubernetes.io/part-of: detective-bot
    detective-bot.io/deployment-phase: foundation
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: detective-bot-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
