apiVersion: v1
kind: Secret
metadata:
  name: detective-bot-secrets
  namespace: private
  labels:
    app.kubernetes.io/part-of: detective-bot
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://REPLACE_USER:REPLACE_PASSWORD@detective-bot-postgres.private.svc.cluster.local:5432/REPLACE_DB"
  TELEGRAM_BOT_TOKEN: "REPLACE_ME"
  VK_GROUP_TOKEN: "REPLACE_ME"
  VK_GROUP_ID: "REPLACE_ME"
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "REPLACE_ME"
